### ISSUE TITLE
TRANSFER | Account Balance not Updated

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/chrome-extension-wallet#102]
Account balance not updated after a successful cross-account transfer. 

Screenshot:

<img width="1208" alt="Screen Shot 2021-07-04 at 9 17 09 PM" src="https://user-images.githubusercontent.com/5258417/124417104-49f46980-dd0d-11eb-846f-787d6116f8ca.png">

URL: https://explorer.harmony.one/#/address/one154774x02yapmrr6cj3pppz44vk80kfuf28rsgd

Step to Reproduce:

1/ create a brand new 1wallet account
2/ transfer any amount of one tokens from an account (created using harmony chrome wallet extension) to the 1wallet account
3/ check out account balance in explorer (not updated after 17 mins)
4/ check out account balance in https://1wallet.crazy.one/wallets

**Comment by ethlocker** [comment]
This repo is not the right place to ask about 1wallet.crazy.one.

**Comment by AndyBoWu** [comment]
Then, which repo should I submit the bug to?

**Comment by lijiang2087** [comment]
> Then, which repo should I submit the bug to?

https://github.com/polymorpher/one-wallet
