### ISSUE TITLE
PRODUCT | Please Clearly Stated Which Authenticator Should be Used

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/chrome-extension-wallet#103]
I discovered this issue when I am testing the `restore` functionality. 

I created my first 1wallet account using [Authy](https://authy.com/) which is as popular as Google Authenticator, if not more. The problem is that the wallet restoring functionality relies on a feature by Google Authenticator to export the account. I could not find this feature in Authy, at least not to my knowledge.

<img width="567" alt="Screen Shot 2021-07-04 at 9 26 17 PM" src="https://user-images.githubusercontent.com/5258417/124417735-aefc8f00-dd0e-11eb-9412-7de6f129ef7a.png">

The problem I'd like to report:

PLEASE clearly ask end users to double check they choose the correct 2FA app!! Otherwise, they won't be able to restore this account.

<img width="1182" alt="Screen Shot 2021-07-04 at 9 22 44 PM" src="https://user-images.githubusercontent.com/5258417/124417681-8b394900-dd0e-11eb-8898-b850ce5c87d7.png">

**Comment by ethlocker** [comment]
This repo is not the right place to ask about 1wallet.crazy.one.

**Comment by AndyBoWu** [comment]
Then, which repo should I submit the bug to?

**Comment by lijiang2087** [comment]
> Then, which repo should I submit the bug to?

https://github.com/polymorpher/one-wallet
