### ISSUE TITLE
PRODUCT | Enforce 2FA to Access Account Once the Previous Tab/Session Closed?

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/chrome-extension-wallet#104]
One potential security concern I have is that this account is open to anyone who has the access to this computer.

Let's say I closed the wallet tab (or even force quit the web browser), the wallet is open to anyone whoever load this wallet webpage. Not a very secure design I think. 

Maybe force user to set a password to re-access? And this password should be essential to do a transfer too IMO.

<img width="1217" alt="Screen Shot 2021-07-04 at 9 39 01 PM" src="https://user-images.githubusercontent.com/5258417/124418721-f97f0b00-dd10-11eb-9482-d222b425b767.png">

**Comment by ethlocker** [comment]
This repo is not the right place to ask about 1wallet.crazy.one.

**Comment by AndyBoWu** [comment]
Then, which repo should I submit the bug to?

**Comment by lijiang2087** [comment]
> Then, which repo should I submit the bug to?

add it here: https://github.com/polymorpher/one-wallet
