### ISSUE TITLE
Transaction hash shows it went through, but the total does not reflect correctly in wallet or on protocol

### ISSUE THREAD

**Issue by doramina11** [harmony-one/chrome-extension-wallet#112]
Transaction hash shows it went through, but the total does not reflect correctly in wallet or on protocol. only one of the two transactions shows. see image for detail.
![image](https://user-images.githubusercontent.com/94941947/145099652-19deff14-97c1-402a-8cf5-3a4c4aa73800.png)

**Comment by givp** [comment]
@doramina11 this is related to RPC issues. Your funds are safe as per Explorer and will appear in your wallet once nodes are back in sync. Please see this update https://www.reddit.com/r/harmony_one/comments/ran9n5/the_state_of_rpc_performance_week_of_dec_6th/
