### ISSUE TITLE
Cannot send ONE from chrome wallet

### ISSUE THREAD

**Issue by DPalmz** [harmony-one/chrome-extension-wallet#119]
no matter the address, whenever I try to send ONE (amounts much smaller than what is in my wallet), I get the error "Error: Transaction confirm failed. Network fee is not enough or something went wrong."

**Comment by nacirabogenschneider** [comment]
Is there already any solution here??

**Comment by nacirabogenschneider** [comment]
I have found the bug, you have to set the Gas Price from 1 to 30, this will solve the Problem. This was changed due to a code merge a few days ago.

**Comment by givp** [comment]
Thanks @nacirabogenschneider - this has already been added and will go out in the next update: https://github.com/harmony-one/chrome-extension-wallet/pull/122

**Comment by DPalmz** [comment]
Thanks, I appreciate someone finding a solution. I was able to send ONE
sucessfully.
