### ISSUE TITLE
[BUG/issue] unlocking some of the wallets

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/chrome-extension-wallet#78]
i have 4 wallets on the 1wallet and now it's asking for all my password. i can access 3 of them 4, but not the 4th one. can i just have an option to NOT unlock that one, but get access to the 3 i do know.

**Comment by lijiang2087** [comment]
specifically the first 3 wallets i can unlock, but if there is 1 wallet user cannot unlock, then there should be a way to bypass that and just not add that 4th wallet, but still be able to use the 1wallet extension with just the 3 wallets i could unlock.

**Comment by rooiie** [comment]
as of the recent version(v1.2.4) the onewallet uses a pin for all wallets inside. if you want to do a transaction you will have to use the password for the specified wallet.

**Comment by yelllowsin** [comment]
> as of the recent version(v1.2.4) the onewallet uses a pin for all wallets inside. if you want to do a transaction you will have to use the password for the specified wallet.

thanks for checking, closing this one. If issue remains, please reopen it.
