### ISSUE TITLE
Transaction rejected: HRC721

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/chrome-extension-wallet#85]
When I import a wallet using the import account->private key, buying NFT's txs fail:
One Wallet version: **v1.1**

<img width="360" alt="image" src="https://user-images.githubusercontent.com/7217595/104530749-70054080-55eb-11eb-80c2-cc1d08943cb6.png">

This is one example of a failed tx: https://explorer.testnet.harmony.one/#/tx/0x75d31374cfd3c24a88755a4321d3cc129054e8f0451fd92d7a7d68364c97f725

When I create a brand new wallet without the import private key feature, buying NFTs work.

**Comment by rooiie** [comment]
in version 1.2.4 NFT buy with private key imported wallet works

**Comment by yelllowsin** [comment]
> in version 1.2.4 NFT buy with private key imported wallet works

thanks for checking, closing this one.
