### ISSUE TITLE
popup for password input not showing in 1.09

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/chrome-extension-wallet#88]
As stated, the popup doesnt show and the issue starts when onewallet updates and inputting the password doesnt work, eg. nothing happens after hitting confirm.

Then we ask users to clear cache/cookies or redownload the onewallet, then they experience the issue where the popup doesnt even show. 

For now we have no clear solution on that, some somehow manage to get past it at some point, no idea how.

screenshots and info:

https://discord.com/channels/532383335348043777/652353409663631365/806324833167081482

![unknown](https://user-images.githubusercontent.com/55639830/106682618-32c91880-65c3-11eb-806f-3269f14511b2.png)

**Comment by rooiie** [comment]
Tried it on Chrome and brave and the wallet seems to be popping up to confirm.
Tried with a newly created wallet, mnemonic imported wallet and a private key imported wallet, seems to be working all fine with me. version 1.2.4
