### ISSUE TITLE
 One Wallet 1.1.2 can't access menu bar

### ISSUE THREAD

**Issue by err0r711** [harmony-one/chrome-extension-wallet#92]
![Untitled](https://user-images.githubusercontent.com/31262326/108825903-e53d3b80-75c3-11eb-9eae-79c6253f395b.jpg)

win 7, chrome and opera

**Comment by rooiie** [comment]
We are allready in version 1.2.4.
Can't seem to find the issue anymore

**Comment by yelllowsin** [comment]
@rooiie thanks for checking, closing this one.
