### ISSUE TITLE
Invalid hexidecimal string

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/chrome-extension-wallet#94]
I am having an issue using One Wallet 1.1.1 when trying to approve a proposal via Snapshot here:
https://hmny-governance.netlify.app/#/staking-testnet/proposal/QmZrKwfYV6xXb52xupHRpH52tywANJBhrPBPUtJjGDxgkL

As you can see, this proposal is already approved now because when i tried via Metamask it worked.

Detailed error message here:
`Signing by Test 1
one170xqsfzm4xdmuyax54t5pvtp5l5yt66u50ctrp
Data
{"version":"0.1.3","timestamp":"1614359551","space":"staking-testnet","type":"vote","payload":{"proposal":"QmZrKwfYV6xXb52xupHRpH52tywANJBhrPBPUtJjGDxgkL","choice":1,"metadata":{}}}
Password
•••••••••
Reject
Approve
invalid hexidecimal string (arg="value", value="{\"version\":\"0.1.3\",\"timestamp\":\"1614359551\",\"space\":\"staking-testnet\",\"type\":\"vote\",\"payload\":{\"proposal\":\"QmZrKwfYV6xXb52xupHRpH52tywANJBhrPBPUtJjGDxgkL\",\"choice\":1,\"metadata\":{}}}", version=#version)`

![2021-02-27 08 07 49](https://user-images.githubusercontent.com/7217595/109385529-4706e980-78d3-11eb-9a72-2dc0f15e29cb.jpg)

**Comment by sophoah** [comment]
Do you still have the issue @yelllowsin if not let's close that one

**Comment by yelllowsin** [comment]
> Do you still have the issue @yelllowsin if not let's close that one

Hey @sophoah can you please create a new proposal on testnet so I can test this again? Unfortunately I don't have a validator running, so can't create at the moment. Thanks

**Comment by yelllowsin** [comment]
Tested this on latest One Wallet version and could not reproduce the issue anymore, seems to be fixed. Tested voting on: https://gov.harmony.one/#/staking-testnet/proposal/QmeSm7x9JoE1J49ERj8x39tb2Jwbi27wh4WsBXoceSkp3p
